### ISSUE TITLE
Detection COCO format is missing

### ISSUE THREAD

**Issue by franva** [PaddleCV-SIG/PP-Label#10]
From this page, it mentions that for the Detection task, it supports both VOC and COCO, but the format of COCO is not mentioned.

Here is the link:
https://github.com/PaddleCV-SIG/PP-Label/wiki/Dataset-Structure#detection

**Comment by linhandev** [comment]
we are in the process of implementing detection dataste import and export. function and doc will be finallized within two weeks

**Comment by franva** [comment]
looking forward to seeing it

**Comment by linhandev** [comment]
Hi @franva, we have recently added support for im/exporting coco format detection datasets. Maybe try it out.
