### ISSUE TITLE
源码安装 paddlelabel，运行不起来

### ISSUE THREAD

**Issue by glock-fei** [PaddleCV-SIG/PP-Label#104]
Database path: sqlite:///C:\Users\dufei\.paddlelabel\paddlelabel.db
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddlelabel\Scripts\paddlelabel-script.py", line 33, in <module>
    sys.exit(load_entry_point('paddlelabel==0.5.0', 'console_scripts', 'paddlelabel')())
  File "D:\anaconda3\envs\paddlelabel\lib\site-packages\paddlelabel-0.5.0-py3.9.egg\paddlelabel\__main__.py", line 71, in run
    prep_samples()
  File "D:\anaconda3\envs\paddlelabel\lib\site-packages\paddlelabel-0.5.0-py3.9.egg\paddlelabel\api\controller\sample.py", line 131, in prep_samples
    copy(src, dst, make_dir=True)
  File "D:\anaconda3\envs\paddlelabel\lib\site-packages\paddlelabel-0.5.0-py3.9.egg\paddlelabel\task\util\file.py", line 121, in copy
    shutil.copy(src, dst)
  File "D:\anaconda3\envs\paddlelabel\lib\shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "D:\anaconda3\envs\paddlelabel\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\anaconda3\\envs\\paddlelabel\\lib\\site-packages\\paddlelabel-0.5.0-py3.9.egg\\paddlelabel\\sample\\bear\\img\\1.jpeg'

Package                Version
---------------------- -------------
alembic                1.9.0
astor                  0.8.1
attrs                  22.1.0
brotlipy               0.7.0
certifi                2022.12.7
cffi                   1.15.1
charset-normalizer     2.1.1
click                  8.1.3
clickclick             20.10.2
colorama               0.4.6
connexion              2.14.1
contourpy              1.0.6
cryptography           37.0.4
cycler                 0.11.0
Cython                 3.0.0a11
decorator              5.1.1
Flask                  2.2.2
Flask-Cors             3.0.10
flask-marshmallow      0.14.0
Flask-SQLAlchemy       3.0.2
fonttools              4.38.0
greenlet               2.0.1
idna                   3.4
importlib-metadata     5.2.0
inflection             0.5.1
itsdangerous           2.1.2
Jinja2                 3.1.2
jsonschema             4.17.3
kiwisolver             1.4.4
Mako                   1.2.4
MarkupSafe             2.1.1
marshmallow            3.19.0
marshmallow-sqlalchemy 0.28.1
matplotlib             3.6.2
numpy                  1.24.0
opencv-python          4.6.0.66
opt-einsum             3.3.0
packaging              22.0
paddle-bfloat          0.1.7
paddlelabel            0.5.0
paddlepaddle           2.4.1
paddlepaddle-gpu       2.4.1.post116
Pillow                 9.3.0
pip                    22.3.1
protobuf               3.20.0
pycocotoolse           2.0.13
pycparser              2.21
pyOpenSSL              22.0.0
pyparsing              3.0.9
pyrsistent             0.19.2
PySocks                1.7.1
python-dateutil        2.8.2
PyYAML                 6.0
requests               2.28.1
setuptools             65.5.0
six                    1.16.0
SQLAlchemy             2.0.0b4
tifffile               2022.10.10
tqdm                   4.64.1
typing_extensions      4.4.0
urllib3                1.26.13
Werkzeug               2.2.2
wheel                  0.37.1
win-inet-pton          1.1.0
wincertstore           0.2
zipp                   3.11.0

**Comment by glock-fei** [comment]
我尝试把 PaddleLabel-0.5.0\paddlelabel\sample 目录 copy 到 anaconda3\envs 中，启动起来的页面出错：

{
"detail": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.",
"status": 404,
"title": "Not Found",
"type": "about:blank"
}

**Comment by glock-fei** [comment]
已经解决，要把 编译好的 dist 文件 copy 到 anaconda3\envs 就可以了

**Comment by linhandev** [comment]
url not found 应该是缺前端，按照说明的步骤build前端再复制到static文件夹应该是没问题的
