### ISSUE TITLE
语义分割-导出数据集-报错：‘NoneType’ object has no attribute 'split' ,导致无法成功导出数据

### ISSUE THREAD

**Issue by wangyaxings** [PaddleCV-SIG/PP-Label#105]
语义分割，标注结束后，导出数据集时报错出现如下画面：  
<img width="1194" alt="1" src="https://user-images.githubusercontent.com/38448350/209840848-3c4992b6-f84a-4683-a5d2-a496cfb85451.png">
命令行中报如下错误
<img width="785" alt="2" src="https://user-images.githubusercontent.com/38448350/209840865-a1878073-a40f-4ea0-93c2-c1709c763090.png">

另外：  
paddlelabel的微信二维码过期了

谢谢

**Comment by linhandev** [comment]
收到，我下午看一下，二维码可以先用这个

![WeChat Image_20221228164220](https://user-images.githubusercontent.com/29757093/209875263-798ea09a-422b-4605-b401-144251931b12.jpg)

**Comment by linhandev** [comment]
有点奇怪，能看出来是缺少size，但是我们现在的版本导入的时候应该是会读取图片保存size的。你这个运行的是什么版本呢

**Comment by wangyaxings** [comment]
1.在conda环境下使用pip命令直接安装,参照如下链接中如下步骤
https://github.com/PaddleCV-SIG/PaddleLabel/blob/v0.5.0/doc/CN/install.md
![image](https://user-images.githubusercontent.com/38448350/210059767-4c3983c0-3b06-4356-99af-653ac5db47a3.png)

2.使用pip list查看到paddlelabel的版本为0.5.0
![Snipaste_2022-12-30_18-14-56](https://user-images.githubusercontent.com/38448350/210059387-4142bf60-b364-47e3-b784-88bf1748d91c.jpg)

3.其它可以公开的情报 (希望有帮助)
（1）在windows下和wsl中都使用pip安装，都同样存在上述问题；
（2）测试执行了图片分类的标注功能，可以正常导出数据，没有问题；
（3）添加打印调试代码到报错位置（/paddlelabel/task/segmentation.py", line 446）如下图
![image](https://user-images.githubusercontent.com/38448350/210060404-470a045a-ba21-43dd-9165-55c594b37877.png)
打印结果有显示出data 值如下图
![image](https://user-images.githubusercontent.com/38448350/210060324-bfc5ced6-d0b9-47e0-ad30-2b82577097ad.png)
其中size属性为None
查看位于./paddlelabel文件夹下的paddlelabel.db数据库确实所有size值都为NULL

**Comment by linhandev** [comment]
嗯嗯，十分感谢回复。

这个问题应该跟环境关系不大，是导入过程中有图片的大小没读进来。

项目类型是语义分割，导入的时候选择标签格式了吗，还是只导入了图片没有导入标签呢。语义分割有四个导入方法，我定位下是哪一个的问题

**Comment by wangyaxings** [comment]
只导入了图片没有导入标签

**Comment by linhandev** [comment]
嗯嗯，我这看了下那个导入好像找到问题在哪了。

可以装一下我们action build出来的开发版试一下还有没有这个问题，pypi发下一版估计还要几周

安装方式可以参考[这里](https://paddlecv-sig.github.io/PaddleLabel/CN/install.html#%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E5%BC%80%E5%8F%91%E7%89%88)

**Comment by marktlen** [comment]
你好，我遇到了相同的问题

在win10下使用 anaconda 创建环境安装了 python 3.10.8

导出数据时，弹出 ‘NoneType’ object has no attribute 'split' 的报错

并尝试在 https://github.com/PaddleCV-SIG/PaddleLabel/actions/runs/3871466982 下载最新的版本。依然存在这个问题

以下是整个环境的版本
```cmd
(paddleLabel) C:\Users\markpc>pip list
Package                Version
---------------------- ----------
alembic                1.9.1
attrs                  22.2.0
certifi                2022.12.7
charset-normalizer     2.1.1
click                  8.1.3
clickclick             20.10.2
colorama               0.4.6
connexion              2.14.1
contourpy              1.0.6
cycler                 0.11.0
Cython                 0.29.33
Flask                  2.2.2
Flask-Cors             3.0.10
flask-marshmallow      0.14.0
Flask-SQLAlchemy       3.0.2
fonttools              4.38.0
greenlet               2.0.1
idna                   3.4
inflection             0.5.1
itsdangerous           2.1.2
Jinja2                 3.1.2
jsonschema             4.17.3
kiwisolver             1.4.4
Mako                   1.2.4
MarkupSafe             2.1.1
marshmallow            3.19.0
marshmallow-sqlalchemy 0.28.1
matplotlib             3.6.2
numpy                  1.24.1
opencv-python          4.7.0.68
packaging              23.0
paddlelabel            0.5.66
Pillow                 9.4.0
pip                    22.3.1
prompt-toolkit         3.0.36
pycocotoolse           2.0.14
pyparsing              3.0.9
pyrsistent             0.19.3
python-dateutil        2.8.2
PyYAML                 6.0
requests               2.28.1
setuptools             65.5.0
six                    1.16.0
sklearn                0.0.post1
split                  0.4
SQLAlchemy             1.4.46
swagger-ui-bundle      0.0.9
tifffile               2022.10.10
tqdm                   4.64.1
urllib3                1.26.13
wcwidth                0.2.5
Werkzeug               2.2.2
wheel                  0.37.1
wincertstore           0.2

(paddleLabel) C:\Users\markpc>python --version
Python 3.10.8
```

**Comment by linhandev** [comment]
你好，这块是旧版的导入功能存在问题，在0.5.66及之前的开发版需要重新导入一下项目应该可以正常导出。我们刚做了一下数据库方面的升级，在 0.5.67 之后的开发版应该可以实现安装最新开发版之后，直接导出之前的项目不报错。

@marktlen

**Comment by linhandev** [comment]
感谢大佬们的反馈，在PaddleLabel v1.0以上版本这个问题应该已经解决了，如果还遇到这个问题可以reopen这个issue。
