### ISSUE TITLE
指定端口运行错误Backend unavaliable, please make sure backend is running and check ur internet connection.

### ISSUE THREAD

**Issue by zjdormlyq** [PaddleCV-SIG/PP-Label#112]
启动
```paddlelabel --port 8000 --lan```
页面可以正常打开，接口无法访问，请求接口端口还是17995
```
请求 URL: http://192.168.1.2:17995/api/projects
引用者策略: strict-origin-when-cross-origin
临时标头已显示
了解详细信息
Accept: */*
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: POST
Origin: http://192.168.1.2:8000
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl
```

**Comment by linhandev** [comment]
有点奇怪，我试一下

**Comment by linhandev** [comment]
我这边试了一下，本地和局域网都能打开网页，访问 http://ip:8000/api/ui，都能看到东西，后端运行的端口应该是对的，问题应该是前端请后端的时候端口有点问题。感觉咱们现象大概一致，我来修一修

**Comment by linhandev** [comment]
应该是修好了，可以按照[这个流程](https://paddlecv-sig.github.io/PaddleLabel/CN/install.html#%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E5%BC%80%E5%8F%91%E7%89%88)装一下我们最新的**开发版**试一下，现在pypi上的0.5.0版本应该就是8000这个端口不可以，其他的端口都是可以的。8000是我们前端开发的默认端口有点特殊。@zjdormlyq

**Comment by zjdormlyq** [comment]
最新的开发版试了一下，已经解决

**Comment by linhandev** [comment]
> 最新的开发版试了一下，已经解决

感谢反馈
