### ISSUE TITLE
新版本测试:  360报毒

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#116]
版本

```
paddlelabel            0.5.56

https://github.com/PaddleCV-SIG/PaddleLabel/actions/runs/3855661608

```

![1](https://user-images.githubusercontent.com/6490927/211125197-dadd4cec-d0bd-4498-b2a2-bda057ac0b03.png)

虽然是误报
但是报毒的行为 确实存在

**Comment by linhandev** [comment]
阿这。。这个是大概在什么时机报的毒呢，是在刚启动后端的时候还是创建项目的时候呢

**Comment by monkeycc** [comment]
<img width="755" alt="微信截图_20230211075606" src="https://user-images.githubusercontent.com/6490927/218223775-4c573224-1ccc-4592-9b85-d9bb5efb3b0d.png">
启动时候

**Comment by linhandev** [comment]
@ztty8888 腾哥有空研究研究，不过我看paddle其他套件也有这种home目录下存cache的操作，感觉报毒应该不会很普遍🤔
