### ISSUE TITLE
新版本测试: 切换图片按钮,位置有问题,不合理

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#117]
版本

```
paddlelabel            0.5.56

https://github.com/PaddleCV-SIG/PaddleLabel/actions/runs/3855661608

```

![1](https://user-images.githubusercontent.com/6490927/211125304-053e8e91-2cda-4f01-ba71-6b1d7e498558.png)
![1](https://user-images.githubusercontent.com/6490927/211126300-54841fc9-4bf3-4661-b189-da73fdbe9504.png)

切换按钮
理论上来说
不应该放图像上

因为会挡住标签

而且背景黑色  
什么按钮都看不到

**Comment by linhandev** [comment]
这个我们也有注意到，未来版本应该会把翻页和进度条放在一起，将来加上快捷键这个按钮应该不会很常用，可以放在偏一点的地方

**Comment by linhandev** [comment]
新版将翻页按钮的位置放到了页面最下方进度条两侧，并添加了快捷键支持。预计下周会进到开发版
