### ISSUE TITLE
新版本测试: 调整大小,建议增加十字线

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#118]
版本

```
paddlelabel            0.5.56

https://github.com/PaddleCV-SIG/PaddleLabel/actions/runs/3855661608

```

矩形框不能移动
按 编辑 
只能调整大小
但是不能移动
看上去是固定死了
感觉不顺手

如果只能通过调整大小调整位置的话

建议调整大小的时候 
再增加 十字瞄准线
方便调整到对应的位置

现在只能看到点  但是这个点又有个十字格子
具体移动到哪个位置  完全看不清楚

而且移动过程 框最好再透明一点
挡住缺陷了

画框要符合缺陷的大小
但是你这个框又挡住了我的缺陷
不好瞄准

![1](https://user-images.githubusercontent.com/6490927/211125629-3ce04d9c-bcf3-4e2b-93af-7e3abe42a4c2.png)

**Comment by linhandev** [comment]
上一版提升前端流畅度留得技术债，这块让前端同学看下估计最近会优化一下

**Comment by linhandev** [comment]
针对这块的优化已经基本完成，将在下个版本发布

**Comment by lifw555** [comment]
在develop分支依然有这个问题。
https://github.com/PaddleCV-SIG/PaddleLabel/issues/173
