### ISSUE TITLE
新版本测试:导出的YOLO数据集格式, 训练框架应该怎么用?

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#119]
导出的YOLO数据集格式, 训练框架应该怎么用?

比如 PaddleYOLO  Yolov5
配置文件要怎么写

是否在教程中写明？
现在的教程只有PaddleDetection训练VOC

比如我突然想用Yolov5来训练
怎么改Yolov5数据配置？

**Comment by linhandev** [comment]
这块有在计划，目前还没做到这。

一方面文档会完善怎么链接到下游任务，另一方面导出的时候可能会考虑给用户一个选项，比如导出coco格式选择之后再选一个套件，我们一起输出一个数据集的yaml配置
