### ISSUE TITLE
新版本测试: 导入额外数据有问题

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#120]
版本

```
paddlelabel            0.5.56

https://github.com/PaddleCV-SIG/PaddleLabel/actions/runs/3855661608

```

导入
D:/MM
1.jpg
2.jpg
3.jpg
4.jpg
5.jpg
...

再导入
D:/GG
1.jpg
2.jpg
3.jpg
4.jpg
5.jpg
...

然后查看列表
最后一页
发现导入的图片怎么只有3张

导入的机制有问题
是按照文件名称?
还是列表排序问题？

应该设置一个
发现有重命名的
后面新增的图片后面加上 _1 什么的

**Comment by linhandev** [comment]
导入额外是有些问题我们还没仔细测这边。

重名的图片默认是不会导入。感觉这块的行为可以改成默认全都导入之后给用户一个标注任务去重的功能。这块估计还需要点时间来设计和实现
