### ISSUE TITLE
新版本测试: 自动推理设置有问题

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#121]
版本

```
paddlelabel            0.5.56

https://github.com/PaddleCV-SIG/PaddleLabel/actions/runs/3855661608

```

http://localhost:17995/static/index.html#/static/project_ai?taskCategory=detection&projectId=1
自动推理设置
选择模型 报错

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Something went wrong.
undefined is not iterable (cannot read property Symbol(Symbol.iterator))

另外 模型 应该可以自己设置的

比如 选择模型目录
选择是什么框架的模型
比如paddleX的模型

这样就可以实现自定义模型标注了

**Comment by linhandev** [comment]
问题本身看起来是前端，我们研究研究。

近期我们主要在做基础标注体验，现在每类项目基本支持一个模型。后期ml后端会投入更多建设，支持paddle套件模型是一个可能的方向。

**Comment by linhandev** [comment]
@xiaoyixin-cmd 鑫哥可以关注一下在ml后端没起来的时候进行选择模型之类的操作之后的反应，我这边基本上所有操作都会导致网页报错，感觉这里可以做一个类似ml后端不存在，除了ml后端地址之外的所有设置disable置灰

**Comment by xxmd1132** [comment]
我这边也是报同样的错误，PaddleLabel-ML已经开启，访问http://localhost:1234/running网页能看到返回true。但是在http://localhost:17995网页内自动推理设置部分，报了同样的错误：The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Something went wrong.

**Comment by linhandev** [comment]
> 我这边也是报同样的错误，PaddleLabel-ML已经开启，访问http://localhost:1234/running网页能看到返回true。但是在http://localhost:17995网页内自动推理设置部分，报了同样的错误：The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> Something went wrong.

感谢反馈。我们研究了一下，localhost的应该没问题，用局域网ip会报错，这个问题会在下个版本修复

**Comment by ryan-minato** [comment]
Is there any solution to fix this problem, now? 
I have encountered this issue on both Linux and Windows, and have tried to connect to paddlelabel-ml using both the local IP and localhost, but with no success. I even rolled back to version 0.5.0, but there was still no change.

I don't think this is simply a frontend problem. Also, if possible, could you please package both of them together, 
or, could you provide a Docker image instead?

**Comment by Dark1Forest** [comment]
仍然发现异常，我在电脑上部署paddlelabel和paddlelabel-ml，使用局域网中其他电脑访问，配置自动化标注的时候出现错误
`
Something went wrong.
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
`
