### ISSUE TITLE
新版本测试: 项目设置应该显示

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#122]
![1](https://user-images.githubusercontent.com/6490927/211127625-be47d0ee-d413-4602-8a19-c2a4190b2822.png)

已建立的项目
项目设置
什么都不显示

设置的名字和目录都是摆设？

那么我怎么知道这个目录在哪里?

**Comment by linhandev** [comment]
奇怪，之前没主意到这个bug，让前端看看

**Comment by linhandev** [comment]
已经修复
