### ISSUE TITLE
功能需求——已有标注项目无法新增图片

### ISSUE THREAD

**Issue by kevinfu1717** [PaddleCV-SIG/PP-Label#137]
已建立的标注项目，无法添加新的图片进行标注。把新图片拷贝进之前的图片文件夹，点更新，重启paddlelabel也没用。

**Comment by kevinfu1717** [comment]
发现可以通过“项目总览”——“导入额外数据”，输入新增的图片文件夹地址就可以，这时也会更新项目里文件夹中的图片

**Comment by kevinfu1717** [comment]
但是删除旧图片或图片移位后的失效图片还保留在项目中无法删除。。。希望可以增加对失效图片或图片移位后的处理。用了数据库就应该有 增删查改的功能

**Comment by linhandev** [comment]
我们目前是还没有做删除任务的功能，这个在后面的版本会添加
盘上的图片移动之后重新识别我们目前还没有这方面的计划。想问下是什么场景下会有这种情况呢？paddlelabel目前有子集划分的功能
失效图片处理这块我们研究下怎么搞比较好，不过建议导入项目之后不要修改数据集文件夹里的文件

**Comment by kevinfu1717** [comment]
有一个场景情况是：
1.我建了一个263张的标注项目，其中有13张图中是没有标注物的，所以无需标注。paddlelabel前端显示：“ 进度：250/263,当前任务250”。这时输出coco或voc均会报错，报错示例如下：
 File "d:\ProgramData\Anaconda3\envs\paddle21\lib\site-packages\paddlelabel\api\controller\project.py", line 129, in export_dataset
    exporter(export_dir)
  File "d:\ProgramData\Anaconda3\envs\paddle21\lib\site-packages\paddlelabel\task\detection.py", line 479, in coco_exporter
    size = data.size.split(",")
AttributeError: 'NoneType' object has no attribute 'split'
2.所以怀疑上面是因为混有这种无标注物图片导致报错，所以考虑删除图片，或若不删除的话，请问可怎样处理这问题？

**Comment by linhandev** [comment]
感谢回复！

了解，数据集里有没有标注的任务导致不能导出，这是导出模块的bug，我检查下这块。

我们近期准备发布的1.0版本应该没有这个问题，可以按照[文档](https://paddlecv-sig.github.io/PaddleLabel/CN/install.html#%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E5%BC%80%E5%8F%91%E7%89%88)安装一个我们最新的开发版本尝试一下。

**Comment by kevinfu1717** [comment]
感谢及时回复，更新问题情况：
File "d:\ProgramData\Anaconda3\envs\paddle21\lib\site-packages\paddlelabel\api\controller\project.py", line 129, in export_dataset
exporter(export_dir)
File "d:\ProgramData\Anaconda3\envs\paddle21\lib\site-packages\paddlelabel\task\detection.py", line 479, in coco_exporter
size = data.size.split(",")
AttributeError: 'NoneType' object has no attribute 'split'
的报错不确定是否没有全部标注导致的。因为我增加了一个标注类别，把全部标注完后，仍然报这个错，追查问题的表象是：
C:\Users\Administrator\.paddlelabel\paddlelabel.db的data表中的size列中有一大部分是空的，其他就有"1,1723,1723,3"这样的数据，现在正在手动补回那些空的格看看。。。。

**Comment by linhandev** [comment]
嗯嗯，0.5.0有这种问题，如果你用比如coco格式导入，之后用另一个格式，比如voc导出可能会有这种情况。

我们现在的开发版有一个数据库升级的步骤是重新读取所有的size项，安装后启动时会自动触发，可以尝试下。之前导出的步骤size格式好像也有不统一的情况，有些是1,height,width,有些是1,width,height。我们新版全部统一成1,h,w了
