### ISSUE TITLE
能否增加用户登录，用户管理，数据库

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#166]
能否增加用户登录，用户管理，数据库

用户登录
用户管理

本地数据库 或者 mysql 数据库 或者json

**Comment by linhandev** [comment]
目前有sqlite数据库，在 ~/.paddlelabel/paddlelabel.db 。用了orm，支持其他数据库软件应该也不是很复杂。用户功能正在计划，现在有一波bugfix和一个主要的数据库依赖升级在做，做完之后应该就是多用户支持
