### ISSUE TITLE
有没API的

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#167]
比如我有一个图片文件夹路径

想用python来创建项目

比如分类

只要提交给PaddleLabel 4个参数
```
项目名称
数据集路径
项目描述
分类项目类型 
```

PaddleLabel就可以自动读取路径
然后走创建项目的流程

**Comment by linhandev** [comment]
有，加-d调试模式启动，访问 /api/ui路径可以看到所有的api。

https://github.com/PaddleCV-SIG/PaddleLabel/tree/v1.0.0/thunder-tests 这个目录下有少量我们调试api用的请求。用vscode thunder插件可以调
