### ISSUE TITLE
放大缩小图片后交互式分割的效果不对

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/PP-Label#17]
由于点击和放大缩小后的图片不对应导致的，click也要进行相应的缩放
![image](https://user-images.githubusercontent.com/35907364/178449092-beda9f7b-7c49-454f-8edd-93c5222c4189.png)
![image](https://user-images.githubusercontent.com/35907364/178449122-51d084e5-eeeb-4a59-b908-d8475a5d5f89.png)

**Comment by linhandev** [comment]
![Image](https://user-images.githubusercontent.com/29757093/182045302-c898057a-bf90-488c-a930-ac9d3a13d329.png)

看起来应该是fix了 @haoyuying
