### ISSUE TITLE
分割保存出错

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/PP-Label#18]
<img width="1440" alt="截屏2022-07-12 16 14 08" src="https://user-images.githubusercontent.com/35907364/178449404-cf60dc84-9f0e-48f2-8b2b-e94014a43070.png">

**Comment by linhandev** [comment]
这个我大概知道问题出在哪，但是不确定为什么。再遇到这个问题可以把.pplabel下的db文件和数据集发过来我导出一下试试

**Comment by linhandev** [comment]
应该是fix了 @haoyuying

**Comment by linhandev** [comment]
表面fix了，深层原因还需要研究 @linhandev

**Comment by linhandev** [comment]
交互式结果宽度不应该是0
