### ISSUE TITLE
交互式点击显示有问题

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/PP-Label#19]
<img width="495" alt="截屏2022-07-12 15 57 41" src="https://user-images.githubusercontent.com/35907364/178449601-416b0473-eadc-4c51-8c8e-f55cd3bdc387.png">
<img width="1000" alt="截屏2022-07-12 16 03 34" src="https://user-images.githubusercontent.com/35907364/178449644-9e2e1e5f-5bfc-4152-ad45-06938696bbf5.png">

**Comment by linhandev** [comment]
fixed
