### ISSUE TITLE
字符识别项目下无法进行多边形和矩形的创建

### ISSUE THREAD

**Issue by shenxiancf12** [PaddleCV-SIG/PP-Label#193]
多边形体现在左键定好坐标后点击右键并不会生成遮掩区，毫无反应
矩形体现在刚点下左键就创建好了待识别区，没法进行后续拖拽生成遮掩区，会直接变为拖拽画面操作
此问题在其他项目类别中均无发生

**Comment by StandHeo** [comment]
我也遇到这个问题了

**Comment by 1249815869** [comment]
这是因为创建项目时没有选择“导入标注格式”导致的
https://github.com/PaddleCV-SIG/PaddleLabel/issues/223#issuecomment-2229830122 @
