### ISSUE TITLE
ml_backend默认路径改一下，加载上一次的路径会有问题

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/PP-Label#20]
加载上一次路径会弹开，使用体验很差

**Comment by linhandev** [comment]
应该是说浏览器的form fill会让pop up失去focus

**Comment by linhandev** [comment]
![image](https://user-images.githubusercontent.com/29757093/181877854-d29e5407-800d-4b25-980e-b15800d4215d.png)

已经改成 modal @haoyuying
