### ISSUE TITLE
orc 无法标注

### ISSUE THREAD

**Issue by sunnynie** [PaddleCV-SIG/PP-Label#202]
无法使用矩形或者多点进行标注
- 使用矩形，就变成了拖动的效果
- 选择多点标注，无法操作结束，始终无法标注一个区域

**Comment by 1249815869** [comment]
这是因为创建项目时没有选择“导入标注格式”导致的
https://github.com/PaddleCV-SIG/PaddleLabel/issues/223#issuecomment-2229830122 @
