### ISSUE TITLE
'coroutine' object is not callable

### ISSUE THREAD

**Issue by WangShengFeng1** [PaddleCV-SIG/PP-Label#214]
我在安装完启动之后，跳出画面但不能创建数据集，返回终端时看见了这个错误，有没有和我一样的小伙伴？这个错误该怎么解决？
ERROR [uvicorn.error] Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\wang1\anaconda3\envs\paddlelabel\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wang1\anaconda3\envs\paddlelabel\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wang1\anaconda3\envs\paddlelabel\Lib\site-packages\uvicorn\middleware\message_logger.py", line 86, in __call__
    raise exc from None
  File "C:\Users\wang1\anaconda3\envs\paddlelabel\Lib\site-packages\uvicorn\middleware\message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "C:\Users\wang1\anaconda3\envs\paddlelabel\Lib\site-packages\connexion\middleware\main.py", line 501, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\wang1\anaconda3\envs\paddlelabel\Lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    await response(scope, receive, send)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not callable

**Comment by sun-tao** [comment]
请问老哥解决了吗，我也有这个问题

**Comment by MrLinaaa** [comment]
俺也一样

**Comment by AnxysUaen** [comment]
+1

**Comment by dlaoy** [comment]
我也发生同样的错误

**Comment by WangShengFeng1** [comment]
在点赞多的一个评论里的那个方法有用！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddleCV-SIG/PaddleLabel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月18日(星期天) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddleCV-SIG/PaddleLabel] 'coroutine' object is not callable (Issue #214)





 
我也发生同样的错误

**Comment by dlaoy** [comment]
> 在点赞多的一个评论里的那个方法有用！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddleCV-SIG/PaddleLabel" ***@***.***&gt;; 发送时间:&nbsp;2024年2月18日(星期天) 中午11:08 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddleCV-SIG/PaddleLabel] 'coroutine' object is not callable (Issue #214) 我也发生同样的错误 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，其他的issues没看到有发生TypeError: 'coroutine' object is not callable的情况，也没有解决方案，您是指的哪个评论？

**Comment by WangShengFeng1** [comment]
pip install uvicorn==0.14 --no-deps
pip install connexion==2.14.1 --no-deps
pip install anyio==3.0 --no-deps
pip install Werkzeug==2.2.2 --no-deps
pip install starlette==0.21.0 --no-deps
pip install Flask==2.2.2 --no-deps
pip install Flask-Cors==3.0.10 --no-deps
pip install a2wsgi==1.8.0 --no-deps
pip install alembic==1.12.1 --no-deps
pip install a2wsgi uvicorn==0.18.1
我都试了一下，最后成功了，到底是哪是哪个起了作用我也不知道

**Comment by WangShengFeng1** [comment]
pip install uvicorn==0.14 --no-deps
pip install connexion==2.14.1 --no-deps
pip install anyio==3.0 --no-deps
pip install Werkzeug==2.2.2 --no-deps
pip install starlette==0.21.0 --no-deps
pip install Flask==2.2.2 --no-deps
pip install Flask-Cors==3.0.10 --no-deps
pip install a2wsgi==1.8.0 --no-deps
pip install alembic==1.12.1 --no-deps
pip install a2wsgi uvicorn==0.18.1
你可以试试，我不知道为什么，到我这么做成功了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddleCV-SIG/PaddleLabel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月18日(星期天) 中午12:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddleCV-SIG/PaddleLabel] 'coroutine' object is not callable (Issue #214)





  
在点赞多的一个评论里的那个方法有用！
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddleCV-SIG/PaddleLabel" @.&gt;; 发送时间:&nbsp;2024年2月18日(星期天) 中午11:08 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PaddleCV-SIG/PaddleLabel] 'coroutine' object is not callable (Issue #214) 我也发生同样的错误 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你好，其他的issues没看到有发生TypeError: 'coroutine' object is not callable的情况，也没有解决方案，您是指的哪个评论？

**Comment by dlaoy** [comment]
> pip install uvicorn==0.14 --no-deps pip install connexion==2.14.1 --no-deps pip install anyio==3.0 --no-deps pip install Werkzeug==2.2.2 --no-deps pip install starlette==0.21.0 --no-deps pip install Flask==2.2.2 --no-deps pip install Flask-Cors==3.0.10 --no-deps pip install a2wsgi==1.8.0 --no-deps pip install alembic==1.12.1 --no-deps pip install a2wsgi uvicorn==0.18.1 你可以试试，我不知道为什么，到我这么做成功了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddleCV-SIG/PaddleLabel" ***@***.***&gt;; 发送时间:&nbsp;2024年2月18日(星期天) 中午12:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddleCV-SIG/PaddleLabel] 'coroutine' object is not callable (Issue #214) 在点赞多的一个评论里的那个方法有用！ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddleCV-SIG/PaddleLabel" @.&gt;; 发送时间:&nbsp;2024年2月18日(星期天) 中午11:08 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PaddleCV-SIG/PaddleLabel] 'coroutine' object is not callable (Issue #214) 我也发生同样的错误 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 你好，其他的issues没看到有发生TypeError: 'coroutine' object is not callable的情况，也没有解决方案，您是指的哪个评论？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

了解明白。
咱这个错误是coroutine版本不匹配，connexion==2.14.1
随后是flask报错AttributeError: module 'flask.json' has no attribute 'JSONEncoder'，同样重装对应版本，Flask==2.2.2
最后是werkzeug库报错ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (F:\anaconda3\envs\paddlelabel\Lib\site-packages\werkzeug\urls.py)，同样重装对应版本，Werkzeug==2.2.2
装好对应版本就能创建项目了
主要还是版本不匹配啊

**Comment by WangShengFeng1** [comment]
但我最后操作成功我也并没有使用这个进行数据集的标注，这个它标注的时候显示开图片特别慢，并不是很好用。我自己写了一个python,你可以拿去改改，我用这个标注的。
import os
import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox

class ImageLabelingApp:
    def __init__(self, root):
        self.root = root
        self.root.title("图片属性标注工具")

        self.image_folder_path = None
        self.image_names = []
        self.current_index = 0
        self.total_images = 0
        self.labeled_images = 0

        self.label_var_pose = tk.StringVar()
        self.label_var_pose.set("未选择")

        self.label_var_gender = tk.StringVar()
        self.label_var_gender.set("未选择")

        self.label_var_clothing = tk.StringVar()
        self.label_var_clothing.set("未选择")

        # 图片显示区域
        self.canvas = tk.Canvas(root)
        self.canvas.grid(row=0, column=0, rowspan=4, padx=10, pady=10, sticky=tk.NSEW)
        self.canvas.bind("<Configure&gt;", self.resize_image)
        self.canvas.bind("<MouseWheel&gt;", self.zoom_image)

        # 姿势标签和单选按
        self.pose_label_entry = tk.Label(root, text="姿势：", font=('Arial', 14))
        self.pose_label_entry.grid(row=0, column=1, padx=10, pady=5, sticky=tk.W)
        self.radio_pose_stand = tk.Radiobutton(root, text="站", variable=self.label_var_pose, value="1")
        self.radio_pose_stand.grid(row=1, column=1, padx=10, pady=5, sticky=tk.W)
        self.radio_pose_sit = tk.Radiobutton(root, text="坐", variable=self.label_var_pose, value="0")
        self.radio_pose_sit.grid(row=1, column=2, padx=10, pady=5, sticky=tk.W)

        # 性别标签和单选按钮
        self.gender_label_entry = tk.Label(root, text="性别：", font=('Arial', 14))
        self.gender_label_entry.grid(row=2, column=1, padx=10, pady=5, sticky=tk.W)
        self.radio_male = tk.Radiobutton(root, text="男", variable=self.label_var_gender, value="1")
        self.radio_male.grid(row=3, column=1, padx=10, pady=5, sticky=tk.W)
        self.radio_female = tk.Radiobutton(root, text="女", variable=self.label_var_gender, value="0")
        self.radio_female.grid(row=3, column=2, padx=10, pady=5, sticky=tk.W)

        

        # 跳过按钮
        self.skip_button = tk.Button(root, text="跳过", command=self.skip_image, font=('Arial', 14))
        self.skip_button.grid(row=6, column=2, padx=10, pady=5, sticky=tk.W)
        self.root.bind("<s&gt;", lambda event: self.skip_image())  # 绑定按键事件

        # 下一张按钮
        self.next_button = tk.Button(root, text="下一张", command=self.next_image, font=('Arial', 14))
        self.next_button.grid(row=7, column=1, padx=10, pady=5, sticky=tk.W)
        self.root.bind("<Return&gt;", lambda event: self.next_image())

        # 保存标注按钮
        self.save_button = tk.Button(root, text="保存标注", command=self.save_labels, font=('Arial', 14))
        self.save_button.grid(row=8, column=1, padx=10, pady=5, sticky=tk.W)

        # 状态标签
        self.status_label = tk.Label(root, text="", font=('Arial', 12))
        self.status_label.grid(row=9, column=0, columnspan=2, padx=10, pady=10, sticky=tk.W)

        self.load_images()

    def load_images(self):
        # 选择图片文件夹
        self.image_folder_path = filedialog.askdirectory(title="选择图片文件夹")
        if self.image_folder_path:
            self.image_names = [f for f in os.listdir(self.image_folder_path) if f.lower().endswith('.png')]
            self.total_images = len(self.image_names)
            self.show_image()
            self.update_status_label()

    def show_image(self):
        # 显示图片
        if 0 <= self.current_index < len(self.image_names):
            image_path = os.path.join(self.image_folder_path, self.image_names[self.current_index])
            self.image = tk.PhotoImage(file=image_path)
            self.original_image = self.image
            self.display_image = self.canvas.create_image(0, 0, anchor=tk.NW, image=self.original_image)
            self.canvas.config(scrollregion=self.canvas.bbox(tk.ALL))
            self.label_var_pose.set("未选择")
            self.label_var_gender.set("未选择")
            self.label_var_clothing.set("未选择")
            self.auto_fit_image()

    def auto_fit_image(self):
        # 自适应图片大小
        canvas_width = self.canvas.winfo_width()
        canvas_height = self.canvas.winfo_height()

        image_width = self.original_image.width()
        image_height = self.original_image.height()

        if canvas_width < image_width or canvas_height < image_height:
            ratio_w = canvas_width / image_width
            ratio_h = canvas_height / image_height
            ratio = min(ratio_w, ratio_h)

            new_width = int(image_width * ratio)
            new_height = int(image_height * ratio)

            self.image = self.original_image.subsample(int(image_width / new_width), int(image_height / new_height))
            self.canvas.itemconfig(self.display_image, image=self.image)

    def resize_image(self, event):
        # 重新调整图片大小
        self.auto_fit_image()

    def zoom_image(self, event):
        # 禁用滚轮缩放，以避免与自动适应大小冲突
        pass

    def next_image(self):
        # 切换到下一张图片
        self.save_labels()  # 自动保存标注信息
        self.current_index += 1
        if self.current_index == len(self.image_names):
            messagebox.showinfo("提示", "所有图片已标注完成")
            self.root.quit()
        else:
            self.show_image()
            self.update_status_label()

    def save_labels(self):
        # 保存标注信息
        pose_label = self.label_var_pose.get()
        gender_label = self.label_var_gender.get()
        clothing_label = self.label_var_clothing.get()

        if pose_label == "未选择" or gender_label == "未选择" or clothing_label == "未选择":
            messagebox.showinfo("提示", "请先选择所有属性")
        else:
            image_name = self.image_names[self.current_index]
            with open("labels.txt", "a", encoding="utf-8") as file:
                file.write(f"{image_name}\t{pose_label},{gender_label},0,1,0,1,0,0,0\n")
            self.labeled_images += 1

    def update_status_label(self):
        # 更新状态标签
        status_text = f"已标注：{self.labeled_images} / 总图片：{self.total_images} / 未标注：{self.total_images - self.labeled_images}"
        self.status_label.config(text=status_text)

    def skip_image(self):
        # 切换到下一张图片，但不保存标注信息
        self.current_index += 1
        if self.current_index == len(self.image_names):
            messagebox.showinfo("提示", "所有图片已标注完成")
            self.root.quit()
        else:
            self.show_image()
            self.update_status_label()

if __name__ == "__main__":
    root = tk.Tk()
    app = ImageLabelingApp(root)
    root.mainloop()





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月18日(星期天) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddleCV-SIG/PaddleLabel] &#39;coroutine&#39; object is not callable (Issue #214)





  
pip install uvicorn==0.14 --no-deps pip install connexion==2.14.1 --no-deps pip install anyio==3.0 --no-deps pip install Werkzeug==2.2.2 --no-deps pip install starlette==0.21.0 --no-deps pip install Flask==2.2.2 --no-deps pip install Flask-Cors==3.0.10 --no-deps pip install a2wsgi==1.8.0 --no-deps pip install alembic==1.12.1 --no-deps pip install a2wsgi uvicorn==0.18.1 你可以试试，我不知道为什么，到我这么做成功了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddleCV-SIG/PaddleLabel" @.&gt;; 发送时间:&nbsp;2024年2月18日(星期天) 中午12:12 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PaddleCV-SIG/PaddleLabel] 'coroutine' object is not callable (Issue #214) 在点赞多的一个评论里的那个方法有用！ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddleCV-SIG/PaddleLabel" @.&gt;; 发送时间:&nbsp;2024年2月18日(星期天) 中午11:08 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PaddleCV-SIG/PaddleLabel] 'coroutine' object is not callable (Issue #214) 我也发生同样的错误 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 你好，其他的issues没看到有发生TypeError: 'coroutine' object is not callable的情况，也没有解决方案，您是指的哪个评论？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
了解明白。
 咱这个错误是coroutine版本不匹配，connexion==2.14.1
 随后是flask报错AttributeError: module 'flask.json' has no attribute 'JSONEncoder'，同样重装对应版本，Flask==2.2.2
 最后是werkzeug库报错ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (F:\anaconda3\envs\paddlelabel\Lib\site-packages\werkzeug\urls.py)，同样重装对应版本，Werkzeug==2.2.2
 装好对应版本就能创建项目了
 主要还是版本不匹配啊

**Comment by dlaoy** [comment]
可以可以👍 我用这个是因为能将数据集导出COCO格式，就不用脚本转换了

**Comment by xxllp** [comment]
这个官方连个基本的依赖的版本都不写清楚，不就是坑吗
