### ISSUE TITLE
检测标注把标注列表锁住导致无法删除

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/PP-Label#22]
<img width="787" alt="截屏2022-07-12 15 44 10" src="https://user-images.githubusercontent.com/35907364/178450701-b62ca632-bdf4-4ad8-a7f5-ec46fe319cc0.png">

**Comment by linhandev** [comment]
已经修复，有空可以看一下

**Comment by linhandev** [comment]
fixed
