### ISSUE TITLE
在图片上标矩形，图片自动变成移动模式，导致不能标注矩形

### ISSUE THREAD

**Issue by harvee1981** [PaddleCV-SIG/PP-Label#223]
安装过程如下：

conda create -n paddlelabel python=3.11
conda activate paddlelabel
pip install --upgrade paddlelabel
pip install connexion[flask]
pip install uvicorn[flask]==0.18.1
pip install connexion==2.14.1 --no-deps
pip install Flask==2.2.2 --no-deps
pip install Werkzeug==2.2.2 --no-deps
paddlelabel --lan --debug

我尝试了谷歌浏览器、微软Edge、QQ浏览器，都一样的问题。

**Comment by harvee1981** [comment]
无论是群，还是这里提问题，都是石沉大海。 :(

**Comment by xiaolintuoer** [comment]
应该是创建项目的时候没有选中“导入标注格式”选项的问题。
