### ISSUE TITLE
paddlelabel修改自动化标注报错

### ISSUE THREAD

**Issue by Dark1Forest** [PaddleCV-SIG/PP-Label#228]
我在电脑上部署paddlelabel和paddlelabel-ml，使用局域网中其他电脑访问，配置自动化标注的时候出现错误
Something went wrong. undefined is not iterable (cannot read property Symbol(Symbol.iterator))

**Comment by drawyaW** [comment]
> 我在电脑上部署paddlelabel和paddlelabel-ml，使用局域网中其他电脑访问，配置自动化标注的时候出现错误 Something went wrong. undefined is not iterable (cannot read property Symbol(Symbol.iterator))

您好，请问有解决方案了吗，我也是正常启动，浏览器能访问，一输入配置就这样报错😥
