### ISSUE TITLE
安装后启动报错

### ISSUE THREAD

**Issue by Jameswu0624** [PaddleCV-SIG/PP-Label#234]
Starting PaddleLabel
INFO  [paddlelabel.util.189]:
Currently installed paddlelabel version is 1.0.5, a newer version stderr=b"ERROR:Invalidrequirement:'paddlelabel==':Expectedendorsemicolon(afternameandnovalidversionspecifier is available on pypi. Please consider updating paddlelabel with:
    pip install --upgrade paddlelabel
You can visit https://github.com/PaddleCV-SIG/PaddleLabel/blob/develop/doc/CN/release_notes.md to see more details about PaddleLabel updates.
INFO  [paddlelabel.config.19]: Database path: sqlite:///C:\Users\Administrator\.paddlelabel\paddlelabel.db
INFO  [paddlelabel.__main__.119]: Version: 1.0.1
INFO  [paddlelabel.__main__.120]: PaddleLabel is running at http://localhost:17995
Traceback (most recent call last):
  File "\\?\D:\Program Files\Python\Scripts\pdlabel-script.py", line 33, in <module>
    sys.exit(load_entry_point('paddlelabel==1.0.2', 'console_scripts', 'pdlabel')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\paddlelabel\__main__.py", line 122, in run
    connexion_app.run(host=configs.host, port=configs.port, debug=configs.debug)
  File "D:\Program Files\Python\Lib\site-packages\connexion\apps\abstract.py", line 281, in run
    self.middleware.run(import_string, **kwargs)
  File "D:\Program Files\Python\Lib\site-packages\connexion\middleware\main.py", line 497, in run
    uvicorn.run(app, **kwargs)
TypeError: run() got an unexpected keyword argument 'debug'

本地已经执行过pip install --upgrade paddlelabel，扔有这个问题

**Comment by TimesRiver** [comment]
It probably because uvicorn (version 0.20) has removed 'debug' ，try this :  pip install uvicorn==0.18.1
