### ISSUE TITLE
使用PPLabel时遇到的几个问题

### ISSUE THREAD

**Issue by QianZ423** [PaddleCV-SIG/PP-Label#24]
####  1、PPLabel前端页面最上方的导航栏不能自动跳转，需要手动点击刷新按钮。
解释：进入PPLabel的前端页面之后，如果点击“医疗标注”按钮，此时页面会显示Something went wrong，然后我们再点击“欢迎”按钮，页面按道理说会自动跳转，但是实际情况仍然是显示Something went wrong，只有当我们在“欢迎”页面点击浏览器的刷新按钮之后，才可以恢复正常页面，如下图所示：  

![image](https://user-images.githubusercontent.com/48357642/180144859-631cc3e0-97e9-4c20-bf4a-cf1be5cb7c6d.png)
![image](https://user-images.githubusercontent.com/48357642/180145278-425446d8-edcd-4a7e-87ca-ca08a3272389.png)
![image](https://user-images.githubusercontent.com/48357642/180145306-9a004398-db05-48ea-9adf-00bd5b2f8658.png)
  
####  2、PPLabel的“split data”即划分数据集按钮，这里前端页面弹出来的提示框会出现单词字母重叠问题，看着不美观，如下图所示：    
  
![image](https://user-images.githubusercontent.com/48357642/180145545-13f203c0-7bd2-4108-a58c-fa737b9aca70.png)

#### 3、PPLabel在window10上创建数据集的时候一直出现转圈问题，如下图所示：    
  
![image](https://user-images.githubusercontent.com/48357642/180145991-f8d9e286-4c7d-4009-bb34-197e4439d2a9.png)

#### 5、在使用PPLabel的交互式分割的时候，标注完数据导出的时候出现错误，前端页面和终端页面报错提示如下：
  
![image](https://user-images.githubusercontent.com/48357642/180146250-c12ada9b-4fe6-44a4-bd4f-6ed6d2f34c2b.png)
![image](https://user-images.githubusercontent.com/48357642/180146273-261f30df-6e64-47e9-8dcc-29a393908108.png)

**Comment by linhandev** [comment]
2 是翻译的问题，会一起处理

**Comment by linhandev** [comment]
1,2,3已解决

**Comment by linhandev** [comment]
6、PPLabel在使用交互式分割的“智能标注”的时候，右侧数据标注列表里面只有一行标注信息，但是点击“Project overview”之后看到Annotation Count 那一栏显示是2，同样的操作另一张图片，Annotation Count显示又变成了1，也就是说在同样的标注操作下，Annotation Count的值不定？

**Comment by linhandev** [comment]
已经基本解决
