### ISSUE TITLE
pplabel_ml安装问题

### ISSUE THREAD

**Issue by QianZ423** [PaddleCV-SIG/PP-Label#25]
#### 1、我这边在Anaconda中的python3.9的虚拟环境中pip install pplabel_ml的时候一直报错，安装失败（已经在这个虚拟环境中安装过了PaddlePaddle 2.3.1和pplabel 0.0.92），报错信息如下图所示：
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/48357642/180350989-48f3bf23-35a3-4453-9071-7bccf616bf96.png">. 

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/48357642/180351006-3e943c4c-9a31-4d7b-ad1e-3096c5a6956e.png">

**Comment by linhandev** [comment]
单独安装scikit learn试试，大概是装sklearn过程中的问题 @QianZ423

**Comment by linhandev** [comment]
去掉了pdx依赖，如果这回安装成功可以close了 @QianZ423
