### ISSUE TITLE
实例分割的样例有点问题，没有显示样例结果

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/PP-Label#32]
![image](https://user-images.githubusercontent.com/35907364/181476446-f0e953f9-d268-45a9-9962-ebfaf44b25fb.png)
![image](https://user-images.githubusercontent.com/35907364/181476547-88e93854-c3c0-4992-9c7f-cf04f35177be.png)

**Comment by linhandev** [comment]
可能是解决了，polygon是json格式，数据路径是linux下的 /，所以找不到标签。可以再试一下
