### ISSUE TITLE
实例分割导入出错

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/PP-Label#34]
basetask has no attribute imports
![image](https://user-images.githubusercontent.com/35907364/181705372-db3a2e68-6f8c-4b2c-98f3-a31cbb1699a6.png)
导入到seg这个层级
![image](https://user-images.githubusercontent.com/35907364/181705819-7f895747-a896-4561-b500-3371caad80e3.png)

**Comment by linhandev** [comment]
这个看不太出来是什么错误，这块打traceback之前写的有点问题。可以装新版的试一下能不能复现
```shell
pip install --upgrade paddlelabel
```

@haoyuying

**Comment by linhandev** [comment]
在win和linux上貌似两种格式的实例分割不带标签都能导入
