### ISSUE TITLE
[Enhancement] 分割 在笔刷前可视化一个小圆圈，让用户知道目前的直径有多大

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/PP-Label#52]

**Comment by linhandev** [comment]
这个目前是鼠标按下才有笔触大小的可视化，应该调整成进入笔刷工具后，鼠标进入画布就展示笔触大小。 @xiaoyixin-cmd

**Comment by linhandev** [comment]
调整成进入笔刷工具后，鼠标进入画布就展示笔触大小 @xiaoyixin-cmd

**Comment by linhandev** [comment]
> 调整成进入笔刷工具后，鼠标进入画布就展示笔触大小 @xiaoyixin-cmd

已经修复
