### ISSUE TITLE
使用发现的一些问题

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/PP-Label#59]
1. 偶见多边形点位错误，如图：
![image](https://user-images.githubusercontent.com/71769312/182633974-561c3647-f28e-43ce-9cd2-9a1badd7ff0c.png)
（这个我可能发现问题了，在于图片中间那个位置，如果我点一个多边形，然后使用`编辑`，拖动一个点到处动，在中间那个位置就可能失去点）

2. 快速点击出现很多`保存成功`，影响后面的点击，如图：
![image](https://user-images.githubusercontent.com/71769312/182634202-fc9c9f2a-98d3-4686-863b-df9fac910b61.png)

3. 创建多边形的分割后，如果在`项目总览`换成掩膜，之前的多变形还在，且多边形和笔刷都可以使用，如图：
![image](https://user-images.githubusercontent.com/71769312/182635452-a33eb03a-5fed-42a1-aef7-f6064e65c71f.png)

**Comment by linhandev** [comment]
3： 多边形切到掩膜之后，保存时多边形会转成掩膜

后期有在polygon模式下标出一个mask，要求翻页之前转成polygon的计划，因为mask到polygon效果一般不太稳定，希望让用户看到每个效果。polygon到mask自动没什么问题。

感觉可以后期在分割从mask切到polygon的时候弹框问用户要不要把记录都转了

感觉mask模式下允许用polygon还是比较合理的，最后也会转成mask保存，有时候像建筑这种直线比较多的就算要存mask用多边形标可能也比较方便。polygon格式下允许用mask主要是交互式这块需要。

@cheneyveron 
- [ ] 在polygon格式下交互式mask确定轮廓转成polygon
- [ ] 在polygon格式下页面内有mask，在翻页前进行检测，转换，弹框告知用户，没有mask了才允许翻页

**Comment by linhandev** [comment]
2：大概一般不会有人这么干 /笑哭

**Comment by geoyee** [comment]
> 2：大概一般不会有人这么干 /笑哭

感觉有时放大之后可能会稍微比较快的连续点一些点，然后就这个出现就看不到图了，也没法点，是不是限制一下最多出现多少次（比如三次）提示，然后由新的就会覆盖久的那种 🤣

**Comment by geoyee** [comment]
> 3： 多边形切到掩膜之后，保存时多边形会转成掩膜
> 
> 后期有在polygon模式下标出一个mask，要求翻页之前转成polygon的计划，因为mask到polygon效果一般不太稳定，让用户看到每个效果。polygon到mask自动没什么问题。
> 
> 感觉可以后期在分割从polygon切到mask的时候弹框问用户要不要把记录都转了
> 
> 不过感觉mask模式下允许用polygon还可以，最后也会转成mask保存，有时候像建筑这种直线比较多的就算要存mask用多边形标可能也比较方便

了解了

**Comment by linhandev** [comment]
限制了最多6个message，丢掉最旧的
