### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '....\\paddlelabel-0.0.31-py3.7.egg\\paddlelabel\\sample\\bear\\img\\1.jpeg'

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#67]
## 通过 PIP 安装

```shell
pip install --upgrade paddlelabel
```

paddlelabel

`FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Anaconda3\\envs\\PaddleLabel\\lib\\site-packages\\paddlelabel-0.0.31-py3.7.egg\\paddlelabel\\sample\\bear\\img\\1.jpeg'`

**Comment by linhandev** [comment]
您好，我这边在win上尝试了一下没能复现这个问题，不太确定是什么原因。建议您还是用`pip install --upgrade paddlelabel`更新一下最新版，之后如果还是有这个问题去到报错的这个目录下看一眼这个文件是否存在，这可以帮我们更好的定位问题原因。

**Comment by monkeycc** [comment]
pip install --upgrade paddlelabel
可以了

**Comment by linhandev** [comment]
6的，感谢反馈
