### ISSUE TITLE
导出的时候应该可以选择任意数据类型

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#74]
开始选择数据集结构是错误的流程
我选择了 VOC
我想转COCO

怎么办

创建项目的时候   就不应该限制死
不要让用户选择 数据集类型

PaddleLabel 内部统一  
一个PaddleLabel JSON 格式

导出的时候 
可以选择任意数据集类型
VOC  COCO YOLO

流程也就是写死几个固定的转换脚本嘛
对于你们来说  没什么技术难度
PaddleLabel JSON  转 VOC
PaddleLabel JSON  转 COCO 
PaddleLabel JSON  转 YOLO

语义分割与实例分割的  不也可以按照这样转换 导出嘛

**Comment by linhandev** [comment]
> 开始选择数据集结构是错误的流程

创建项目的时候选格式是为了导入已有标签的，你可以试试用一个有标签的数据集创建项目。我们在 ~/.paddlelabel/sample 下有一些样例数据集。

> 我选择了 VOC
> 我想转COCO
> 怎么办

项目的标注格式是可以改的，目前我们在导出的时候没有选择格式，这个计划加。但是目前可以在导出之前先在项目设置里改一下标注格式再导出。

![image](https://user-images.githubusercontent.com/29757093/185539539-c67fa83f-c6c1-4e83-83d6-3056a71f895b.png)

> PaddleLabel 内部统一
> 一个PaddleLabel JSON 格式

我们目前是没有弄一个自己的格式的计划，弄出自己的格式下游的项目可能也导不进去，这样意义不太大。我们会尽量丰富paddlelabel支持的数据集格式，能直接导出那些的话也就没必要先导出再转了。

**Comment by monkeycc** [comment]
导出设置
可以把这个  标注格式  弄到导出设置

这样就不需要回来 更新一次  
没必要 也繁琐了  多此一举

也实现了 自由选择格式的需求

另外可以考虑   
再增加一个  yolo 格式
打造一个通用型的标注工具嘛

**Comment by linhandev** [comment]
yolo会加，那个格式我看不太复杂。

这个创建项目选择标注格式是为了导入标签嘛，这个角度创建的时候选格式是有必要的。感觉可以做成导入的时候不必选，不选的话认为项目只有图片没有标注，之后导出的时候选格式会加。

**Comment by linhandev** [comment]
yolo格式已经添加，导入的时候可选一个数据集格式，如果不选会把所有图片当作待标注任务导入。导出的时候可以选择任意一个支持的格式进行导出
