### ISSUE TITLE
所有类型标注，都应该增加PaddleX模型,半自动标注

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#75]
所有类型标注，都应该增加PaddleX模型半自动标注

加载模型

然后自动标注

可以单张 一张一张
也可以对整个数据集 批量

别用PaddleSeg的EISeg
限制死了 只能用那几个破模型

**Comment by linhandev** [comment]
ml后端有计划添加更多模型，不过做起来有点复杂，所以这一版就上了eiseg一个模型。包括直接在paddlelabel的界面里做简单的训练都有计划。分割的话感觉eiseg效果还行啊 lol

**Comment by monkeycc** [comment]
通用型的话  还是建议 增加一个 paddleX的 半自动标注

eiseg 不能训练自己的模型 来标注

目标检测 也不行

局限性还是很大的

还是考虑用PaddleX来 比较好

我自己训练的模型 再加载标注  多美好

**Comment by linhandev** [comment]
嗯，ml后端其实已经有一个paddlex的分类模型，我们做ml后端用项目内的数据跑训练之后自动推理大概都会先做一个paddlex的。一些特殊的比如交互式分割和自动收框之类的paddlex没有那还是得弄额外的。

近期我们主要集中在基础的标注体验和修bug，ml后端估计要过段时间
