### ISSUE TITLE
已有的Labelme标注的怎么导入数据集,语义和实例

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#77]
Labelme  标注的怎么导入数据集,
语义和实例

1.jpg
1.json

2.jpg
2.json

**Comment by linhandev** [comment]
这个目前大概没有支持的计划，我看labelme coco和voc都可以导出，这俩我们是有支持的

**Comment by monkeycc** [comment]
不能导入确实是一个很大问题

难道还要痛苦  重新标注

可以提供转换工具  
转换为 PaddleLabel 数据集之后
再导入？

**Comment by linhandev** [comment]
感觉可以在labelme导出的时候选一个paddlelabel支持的格式，或者就用labelme转一下，用labelme导入labelme格式再导出成paddlelabel支持的格式

**Comment by monkeycc** [comment]
我是已有的labelme数据  要导入到paddlelabel

所以这个时候 应该是  labelme 转 paddlelabel
导入的时候 可以提供转换的选择  转换的界面  就是增加一个转换工具
 
labelme导出的时候选一个paddlelabel支持的格式
这样你们还要修改labelme才可以  弄一个专门的labelme paddlelabel版本

看怎么样方便了

总不能只要用你们的标注工具 就要全部重新标注吧

**Comment by linhandev** [comment]
重新标注必是不能😂

我研究一下从labelme转现在支持的方不方便，labelme格式可以加支持，要不方便的话考虑最近就做一下

**Comment by monkeycc** [comment]
目标检测一般用  LabelImg 

分割用Labelme  多点标注

其实解决这两个工具的转换   基本上就能通用了

至于 Labelme  其他的 什么线条 点 矩形 都可以先不弄
先确保 分割数据 多点标注  能导入就行了

**Comment by linhandev** [comment]
> 我是已有的labelme数据 要导入到paddlelabel
> 
> 所以这个时候 应该是 labelme 转 paddlelabel 导入的时候 可以提供转换的选择 转换的界面 就是增加一个转换工具
> 
> labelme导出的时候选一个paddlelabel支持的格式 这样你们还要修改labelme才可以 弄一个专门的labelme paddlelabel版本
> 
> 看怎么样方便了
> 
> 总不能只要用你们的标注工具 就要全部重新标注吧

这块我重新研究了一下，如果目前手上有一个labelme格式的数据集，labelme是提供了转coco和voc的脚本，在这 https://github.com/wkentaro/labelme/tree/main/examples/instance_segmentation

这样可以先用脚本转一下，之后coco/voc我们就都能导入了

**Comment by monkeycc** [comment]
能否这样

导入分割数据

2个选择

COCO格式 
labelme格式( Annotations(JSON),JPEGImages (IMG))

这样就不需要用户
还要手动转换一次

**Comment by linhandev** [comment]
可以考虑支持，但是这块需要单独开发。可能我们可以用labelme那边提供的脚本先把labelme的转成coco之后再导入。我研究研究，可能下个月加一下labelme格式

**Comment by monkeycc** [comment]
```
paddlex --data_conversion --source labelme --to MSCOCO--pics ./pics --annotations ./annotations --save_dir ./converted_dataset_dir

paddlex --split_dataset --format COCO --dataset_dir D:\MyDataset --val_value 0.2 --test_value 0.1
paddlex --split_dataset --format SEG --dataset_dir D:\MyDataset --val_value 0.2 --test_value 0.1


https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/data/convert.md
标注数据格式转换

https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/data/split.md
数据划分

```
直接用PaddleX的脚本改改就好了
反正自家产品 怎么用都行

**Comment by linhandev** [comment]
这么说labelme也有这脚本😂
直接用外部的脚本会有一些问题，如果数据很多，paddlelabel需要一份，导出coco需要一份，最后转labelme还有一份，可能会炸盘。
做这个功能的话大概还是直接我们内部格式到labelme自己写

**Comment by linhandev** [comment]
直接导入coco大概一两个星期之后我们完善好现有的导入导出之后会加
