### ISSUE TITLE
导入目标VOC数据集的错误,根据xml图片路径导致读取报错

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#80]
经过数据划分之后
```
Annotations
JPEGImages
labels.txt
test_list.txt
train_list.txt
val_list.txt
```

导入 报错
```

[ WARN:2@446.888] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('E:\MM\1.jpg'): can't open/read file: check file path/integrity
Create project failed
Traceback (most recent call last):
  File "D:\anaconda308\lib\site-packages\paddlelabel\api\controller\project.py", line 77, in post_add
    _import_dataset(new_project)
  File "D:\anaconda308\lib\site-packages\paddlelabel\api\controller\project.py", line 70, in _import_dataset
    importer(data_dir)
  File "D:\anaconda308\lib\site-packages\paddlelabel\task\detection.py", line 444, in voc_importer
    s = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

```

原因是 标注的XML
```
<annotation>
	<folder>0000QBU_MB2</folder>
	<filename>CJ_1_01_1.jpg</filename>
	<path>E:\MM2\CJ_1_01_1.jpg</path>
```

E:\MM2\CJ_1_01_1.jpg  这里不存在

问题就是出现在这里

我都生成
test_list
train_list
val_list
不应该按照我的生成文本来看  图片文件在哪里吗
就算不根据这些
也能根据
Annotations
JPEGImages
这两个文件夹 对应的图片和xml

不应该根据XML的<path>地址来
我标注完成了  文件夹就不能移动了？？
也不能发给别人 因为路径会不对
这个肯定是不对的

**Comment by linhandev** [comment]
这块用的肯定是相对路径，具体细节我查一下

**Comment by linhandev** [comment]
我看了一下，目前的实现是
```shell
<annotation>
	<folder>0000QBU_MB2</folder>
	<filename>CJ_1_01_1.jpg</filename>
	<path>E:\MM2\CJ_1_01_1.jpg</path>
```
用创建项目的时候指定的数据集文件夹，folder的值和filename拼出和标签对应的图片路径。path这个项在导入和导出的过程中都没用到。感觉这块现在的版本呢应该是不存在这个问题。可以等过两天我们发新版了再试一下，或者也可以直接拉后端代码在develop分支上跑一下

**Comment by linhandev** [comment]
大佬我们最近对导入导出进行了一波升级，目前voc格式的导入会顺序使用三个逻辑进行图片和标注的对应，[这里](https://paddlecv-sig.github.io/PaddleLabel/CN/project/detection.html#pascal-voc) 有详细的介绍。新版对数据集格式的要求松了很多。感兴趣的话可以装一个我们的开发版试一下，安装流程在[这里](https://paddlecv-sig.github.io/PaddleLabel/CN/install.html#%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E5%BC%80%E5%8F%91%E7%89%88)有介绍

**Comment by linhandev** [comment]
大佬就这个issue描述的问题还存在不，解决了的话可能可以close了
