### ISSUE TITLE
与PaddleOCR结合

### ISSUE THREAD

**Issue by ZTurboX** [PaddleCV-SIG/PP-Label#84]
后续会和PaddleOCR结合吗，目前PaddleOCR的标注工具不是网页端的

**Comment by linhandev** [comment]
有这方面的计划

**Comment by linhandev** [comment]
ocr项目的支持已经做的差不多了，目前正在测试，预计几周后会在pypi版本上更新。现在可以安装我们的开发版体验，具体步骤参考[这里](https://paddlecv-sig.github.io/PaddleLabel/CN/install.html#%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E5%BC%80%E5%8F%91%E7%89%88)
